language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

install: composer install
script:
  - ./vendor/bin/phpspec run
  - ./vendor/bin/phpcs --standard=PSR2 src/